version: '3.3'

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    kafkamgr:
        container_name: kafkamgr
        environment:
            APPLICATION_SECRET: letmein
#            BASE_ZK_PATH:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            CONSUMER_PROPERTIES_FILE: /usr/local/cmak/conf/consumer.properties
            KAFKA_MANAGER_PASSWORD_FILE: /run/secrets/kafka_manager.pwd
            KAFKA_MANAGER_USERNAME: admin
            KAFKA_MANAGER_AUTH_ENABLED: 'false'
            KAFKA_MANAGER_LOGLEVEL: INFO
#            KM_HTTP_CONTEXT: /
            KM_HTTP_CONTEXT: /kafkamgr
            ZK_HOSTS: zookeeper:2181
        hostname: kafkamgr
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/kafka-manager/${KM_VERSION:-3.0.0.5}:${CONTAINER_TAG:-latest}
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - 9000:9000
        restart: unless-stopped               # only use when building a 'service container'
        secrets:                              # references to 'secrets' section below 
            - kafka_manager.pwd
        volumes:
            - ./vols/log:/usr/local/cmak/home             # do not save aplication logs inside container 

# secrets only needed for deploy
secrets:
   kafka_manager.pwd:
     file: ~/.inf/secrets/bobb.password
