version: '3.3'

services:
    broker:
        command: kafka broker
        container_name: broker
        depends_on:
            - zookeeper
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            KAFKA_ADVERTISED_HOST_NAME: 255.255.255.255
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://255.255.255.255:9092
            KAFKA_BROKER_ID: 3
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_ZOOKEEPER_CONNECT: ubuntu-s1:2181,ubuntu-s4:2181,ubuntu-s3:2181
            ZOOKEEPER_TIMEOUT: 6000
        extra_hosts:
            - "ubuntu-s1:10.1.3.11"
            - "ubuntu-s2:10.1.3.12"
            - "ubuntu-s3:10.1.3.6"
            - "ubuntu-s4:10.1.3.10"
        hostname: broker
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/kafka/${KAFKA_VERSION:-2.2.0}:${CONTAINER_TAG:-a816ff08cbab6b2263a33bc0a9aceea8c1c93b79198a2b6a314aa38882df0a39}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        links:
           - zookeeper
        ports:
            - "9092:9092"
        restart: unless-stopped
        volumes:
            - ./kafka-broker/data:/usr/local/kafka/data
            - ./kafka-broker/logs:/usr/local/kafka/logs
            - ./kafka-broker/log:/var/log

    zookeeper:
        command: kafka zookeeper
        container_name: zookeeper
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            ZOOKEEPER_MY_ID: 3
            ZOOKEEPER_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 10
            ZOOKEEPER_SYNC_LIMIT: 5
        extra_hosts:
            - "ubuntu-s1:10.1.3.11"
            - "ubuntu-s2:10.1.3.12"
            - "ubuntu-s3:10.1.3.6"
            - "ubuntu-s4:10.1.3.10"
        hostname: zookeeper
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/kafka/${KAFKA_VERSION:-2.2.0}:${CONTAINER_TAG:-a816ff08cbab6b2263a33bc0a9aceea8c1c93b79198a2b6a314aa38882df0a39}
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
        ports:
            - "2181:2181"
        restart: unless-stopped
        volumes:
            - ./kafka-zookeeper/data:/usr/local/kafka/data
            - ./kafka-zookeeper/logs:/usr/local/kafka/logs 
            - ./kafka-zookeeper/log:/var/log
