version: '3.5'

services:
    jobmanager:
        command: jobmanager
        container_name: jobmanager
        environment:
            - |
              FLINK_PROPERTIES=
              jobmanager.rpc.address: jobmanager
              env.log.dir: /var/log
              partition-discovery.interval-millis: 1000
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/flink:${FLINK_VERSION:-1.13.0-scala_2.11}
        hostname: jobmanager
        networks:
            - kafka-net
        ports:
            - "8081:8081"
        restart: unless-stopped
        volumes:
            - ./jobmanager/log:/var/log


    taskmanager:
        command: taskmanager
#        container_name: taskmanager
        depends_on:
            - jobmanager
        environment:
            - |
              FLINK_PROPERTIES=
              env.log.dir: /var/log
              jobmanager.rpc.address: jobmanager
              taskmanager.numberOfTaskSlots: 1
              high-availability: zookeeper
              high-availability.zookeeper.path.root: /flink
              high-availability.cluster-id: /flink_ns
              high-availability.zookeeper.quorum: s3.ubuntu.home:2181,s4.ubuntu.home:2181,s8.ubuntu.home:2181
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/flink:${FLINK_VERSION:-1.13.0-scala_2.11}
#        hostname: taskmanager
        networks:
            - kafka-net
        restart: unless-stopped
        scale: 2
        volumes:
            - ./taskmanager/log:/var/log
